import type { BudgetCategoryId } from '../budgetTypes';
import type { ScenarioTier } from './types';

/**
 * Curated lines per category and tier. Games pick by category + resolved tier.
 * Each tier has six options so repeats are less obvious.
 */
export const BUDGET_SCENARIO_LINES: Record<
  BudgetCategoryId,
  Record<ScenarioTier, readonly string[]>
> = {
  emergencyFund: {
    excellent: [
      'A layoff hits; your fund covers months without touching long-term savings.',
      'Back-to-back surprises land; you cash-flow both from the cushion.',
      'You sleep through a market dip because liquidity is sorted.',
      'Family emergency out of state; flights and hotels do not become debt.',
      'You negotiate a job offer calmly because runway exists.',
      'The fund plus insurance deductible means no panic when the storm hits.',
    ],
    good: [
      'A $900 repair stings once, then it is over — no card balance.',
      'You rebuild the fund in a few paychecks after a real withdrawal.',
      'Small shocks are boring: the fund eats them quietly.',
      'Pet vet bill lands; annoying, not catastrophic.',
      'You trim discretionary for one month and the fund is whole again.',
      'Tax bill slightly higher than expected; you absorb it without rotating balances.',
    ],
    bad: [
      'A surprise bill lands on a card; you feel interest starting to nibble.',
      'You scrape by this month, but the cushion is thinner than you like.',
      'You borrow from “next month’s you” to close a gap.',
      'One medium shock wipes half the fund; the next one has nowhere to land.',
      'You keep “almost enough” and learn almost is not enough.',
      'You meant to refill the fund; lifestyle quietly ate the refill.',
    ],
    terrible: [
      'Two shocks in one month: savings gone, then high-APR borrowing.',
      'You skip the fund to splurge; the very next week proves why that hurts.',
      'An emergency becomes a payment plan you will carry for seasons.',
      '401k loan or hardship withdrawal feels like relief; the tax bite waits.',
      'You crowdsource or beg because the account read zero when it mattered.',
      'Every new expense triggers fight-or-flight; sleep is collateral damage.',
    ],
  },
  rent: {
    excellent: [
      'Your place is solid; urgent fixes get handled fast, rent predictable.',
      'Renewal comes with a small freeze you negotiated calmly.',
      'You are housed without drama; headspace goes to goals, not leaks.',
      'Rent is well under one-third of take-home; you actually save after bills.',
      'Neighbors are fine; walls are quiet enough to work from home.',
      'You have a small move-out fund so deposits and trucks are not a crisis.',
    ],
    good: [
      'Rent is on time; minor issues get fixed within a reasonable window.',
      'You chose a place that fits income; housing is a line item, not a crisis.',
      'Roommates or a smaller unit kept rent sane; you are not house-poor.',
      'Rent hikes were expected; you had a plan before the notice arrived.',
      'Utilities stay in a normal band; no mystery drafts or ancient HVAC.',
      'You read the lease once and understood fees; no gotchas yet.',
    ],
    bad: [
      'Heat sputters; the reply is “not urgent” while you layer sweaters indoors.',
      'You are one late fee from real stress; the mailbox feels hostile.',
      'You stretch for “prestige” rent; other buckets quietly starve.',
      'Parking or pet fees creep every year; “base rent” was a fairy tale.',
      'Roommate drama threatens the lease; stability feels fragile.',
      'You are always chasing the first by a few days; stress compounds.',
    ],
    terrible: [
      'Pipe burst, deposit fight, and a week on a couch — housing became the boss.',
      'Mold, ignored requests, and a lease trap: you pay to feel unsafe.',
      'Eviction-adjacent math: you are choosing between rent and food.',
      'Illegal rent hike or deposit theft; you fight while broke.',
      'Unsafe building; leaving costs money, staying costs health.',
      'Doubled-up with family; dignity and savings both take collateral damage.',
    ],
  },
  food: {
    excellent: [
      'Meal prep and bulk buys keep you fed well with room for friends.',
      'Groceries are planned; takeout is a choice, not a panic reflex.',
      'You eat enough protein and vegetables without obsessing over pennies.',
      'Farmers market splurge fits the line; quality and budget shake hands.',
      'Kids get consistent lunches; no scramble for loose change at dawn.',
      'You keep staples stocked so “nothing to eat” never triggers a $40 order.',
    ],
    good: [
      'Most weeks hit the grocery list; occasional treats stay guilt-free.',
      'You batch-cook twice a week; weekday dinners stop being improvised.',
      'A simple “capsule menu” keeps spending predictable.',
      'You use a list app; impulse buys dropped without feeling deprived.',
      'Leftovers get a second life; waste and cost both shrink.',
      'Coffee is mostly home; cafe visits are intentional, not automatic.',
    ],
    bad: [
      'You skip meals to stretch cash; focus and mood slide at work.',
      'The pantry goes empty mid-week; convenience fees stack fast.',
      'Cheap calories spike; energy crashes and cravings take over.',
      'Work lunches bleed cash; you “did not have time” twelve times.',
      'Diet restrictions meet tight budget; safe food costs more stress.',
      'Roommates eat your groceries; resentment and hunger share the fridge.',
    ],
    terrible: [
      'Pantry empty, overdraft snacks, and shame at the register.',
      'You ration basics while subscriptions quietly drain the account.',
      'Food insecurity meets delivery apps: expensive calories, zero plan.',
      'Kids ask what is for dinner; you deflect because the answer is debt.',
      'Food bank line feels like failure; pride costs more than the trip.',
      'Allergic reaction from cheap substitutes; cheap became expensive.',
    ],
  },
  transportation: {
    excellent: [
      'A maintenance fund exists; tires and brakes are scheduled, not disasters.',
      'Transit plus occasional rideshare keeps you reliable and on budget.',
      'You right-sized the car; insurance and fuel are boring numbers.',
      'Roadside kit and spare tire are real; a flat is fifteen minutes, not a saga.',
      'You compare insurance yearly; same coverage, lower premium.',
      'E-bike or bus pass covers 80% of trips; the car is for when it matters.',
    ],
    good: [
      'Oil changes and inspections happen on time; small fixes stay small.',
      'You carpool or bike sometimes; the commute cost trends down.',
      'Parking and tolls are budgeted; no mystery spikes.',
      'Winter tires on schedule; ice storms are weather, not bankruptcy.',
      'You track mileage for taxes; some of the gas comes back.',
      'One reliable vehicle; no payment on a second “just in case” ego car.',
    ],
    bad: [
      'Check-engine light ignored until a tow bill teaches a lesson.',
      'You defer a cheap fix; rental + labor eats a whole paycheck.',
      'Gas prices spike; you have no slack in the line.',
      'Registration expired; tickets stack while you “deal with it later.”',
      'Uber becomes the commute; surge pricing owns your mornings.',
      'Insurance lapsed a week; that was the week of the crunch.',
    ],
    terrible: [
      'The car dies on the commute; shifts lost, predatory financing for repairs.',
      'Uninsured fender-bender: you are biking in winter or paying forever.',
      'License issues stack fees; mobility becomes a money trap.',
      'Repossession tow at 2 a.m.; work and childcare both wobble.',
      'Hit-and-run with no coverage; you pay for someone else’s panic.',
      'Transit pass lapses same day the car fails; you miss payroll.',
    ],
  },
  miscFun: {
    excellent: [
      'Fun money is real and planned: hobbies, rest, no binge-and-regret.',
      'You say yes to small joys weekly without touching emergency savings.',
      'Burnout buffer exists; you recharge before you snap-spend.',
      'Concert tickets were saved for; the night is joy, not regret.',
      'You take PTO without buying luxury; rest was the luxury.',
      'Board game night costs almost nothing; laughter was the line item.',
    ],
    good: [
      'You pick one treat category and enjoy it without guilt.',
      'Cheap fun wins: parks, libraries, friends’ kitchens.',
      'You skip one big splurge and keep weekly micro-joy.',
      'Streaming stays within the fun cap; no stack of ten services.',
      'Hobby supplies hit a monthly max; creativity works inside borders.',
      'You host instead of going out; social life survives the budget.',
    ],
    bad: [
      'Zero fun budget; you white-knuckle until a weekend blows the plan.',
      'Retail therapy after stress; the hangover is financial.',
      'You “deserve it” every rough day; the card remembers all of them.',
      'FOMO events stack; each “just this once” becomes twelve.',
      'Night out creep: pregame, ride, drinks, ride — math left at home.',
      'Kids’ activities become status arms race; resentment builds.',
    ],
    terrible: [
      'Burnout meets impulse: a cart of stuff you will not use in a month.',
      'Gambling-adjacent dopamine hits: wins rare, losses loud.',
      'Fun becomes debt: vacations on cards you cannot pay off.',
      'Relationship fights over money; “fun” was the spark and the fuel.',
      'Buy tickets you cannot afford to sell later at a loss.',
      'Hobby gear collects dust while minimum payments eat the future.',
    ],
  },
  highInterestDebt: {
    excellent: [
      'Cards cleared; old minimums auto-route to investments.',
      'You refinanced toxicity away; breathing room shows up in sleep.',
      'Interest stopped being a second rent payment.',
      'Credit score rebound unlocks cheaper insurance and housing options.',
      'You teach a friend the avalanche method; clarity pays forward.',
      'Promo periods used once, paid off on time — no trap door.',
    ],
    good: [
      'Avalanche plan is working; balances shrink every statement.',
      'You stopped adding new charges while paying old ones down.',
      'One toxic line is gone; the snowball is real.',
      'Balance transfer saved interest; you are paying principal now.',
      'Windfall went to debt, not gadgets; the trend line bent.',
      'You cut one subscription and redirected cash to the worst APR.',
    ],
    bad: [
      'Minimums only; most of the payment feeds APR, not principal.',
      'You shuffle balances without changing habits; the treadmill hums.',
      'Late once; fees and rate hikes make the hole deeper.',
      'Store cards multiply; every checkout offered “save 10% today.”',
      'You hide statements from a partner; shame compounds interest.',
      'Debt consolidation without behavior change; balances creep back.',
    ],
    terrible: [
      'Missed payments stack; collectors add stress to every other problem.',
      'Cash advances to pay cards: the spiral has a name.',
      'You borrow to service debt; math is no longer on your side.',
      'Wage garnishment or lien talk enters the chat; panic is hourly.',
      'Payday loan to cover minimums; APR becomes a sick joke.',
      'Bankruptcy consult feels like the only door; pride fights the knob.',
    ],
  },
  investments: {
    excellent: [
      'Broad index contributions run on autopilot; boring is the feature.',
      'Employer match captured; time in market beats timing.',
      'You invest after basics are funded; compounding has a runway.',
      'Asset allocation matches age and risk; you rebalance without drama.',
      'Dividends reinvest quietly; decades notice what days forget.',
      'You max tax-advantaged space before taxable; order of operations is clean.',
    ],
    good: [
      'Small recurring buys continue even in choppy months.',
      'You learn fees and funds; costs drop, discipline rises.',
      'You increased contributions after a raise — lifestyle creep blocked.',
      'You wrote an IPS on one page; fewer impulse moves.',
      'Bonds in the mix when it matched your timeline; sleep improved.',
      'You ignore hot tips; index funds do the heavy lifting.',
    ],
    bad: [
      'You “invest” while toxic debt still charges high APR.',
      'Concentrated bets replace a plan; stress replaces sleep.',
      'FOMO entries at tops; patience never got a seat.',
      'Robinhood notifications drive decisions; dopamine wrote the plan.',
      'You sell the dip; textbook mistake, real pain.',
      'Crypto as emergency fund; volatility laughs at the label.',
    ],
    terrible: [
      'Leveraged trades wipe savings while debt still breathes down your neck.',
      'You chase hype every cycle; fees and losses compound the wrong way.',
      'Retirement accounts raided for lifestyle; penalties become permanent.',
      'Margin call at the worst hour; broker sells you out at the bottom.',
      'Ponzi-adjacent “guaranteed yield”; trust evaporates with the principal.',
      'You levered real estate and stocks; correlation hits one bad month.',
    ],
  },
  medical: {
    excellent: [
      'HSA funded; preventive care catches something early and cheap.',
      'You fill scripts on schedule; chronic stuff stays managed.',
      'Network and plan understood before you need them urgently.',
      'Dental cleanings on calendar; small cavities never become crowns.',
      'Therapy copay budgeted; mental health is maintenance, not crisis.',
      'FSA used, not forfeited; glasses and labs planned, not rushed.',
    ],
    good: [
      'Copays are planned; urgent care is a budget line, not a panic.',
      'You actually schedule the annual visit; small issues stay small.',
      'Generic swaps where safe; pharmacy bills shrink.',
      'You checked in-network before the specialist; surprise avoided.',
      'Medical bills on a payment plan at 0%; dignity and math intact.',
      'Vision and dental riders justified by usage; no sticker shock.',
    ],
    bad: [
      'You delay a visit; a small symptom becomes urgent care + labs.',
      'Prescriptions rationed; recovery stretches and costs balloon.',
      'Surprise bill arrives; you are negotiating from weakness.',
      'Out-of-network anesthesiologist; the surgery was in-network, the joke was not.',
      'High deductible plan with no HSA fill; every sniffle feels expensive.',
      'Mental health visits capped; you stretch sessions too thin.',
    ],
    terrible: [
      'No buffer for meds; you skip doses or skip follow-ups.',
      'Emergency room as primary care; every visit is a financial event.',
      'Insurance lapse week meets injury; the bill defines the year.',
      'Chronic condition unmanaged; work absences cost more than care would have.',
      'Crowdfunding for a procedure; dignity traded for survival.',
      'Medical debt on cards; health and wealth both bleed.',
    ],
  },
  personal: {
    excellent: [
      'Phone plan right-sized; wardrobe maintained on a small annual line.',
      'Subscriptions audited quarterly; only tools you use remain.',
      'You repair instead of replace when it is sane; upgrades are planned.',
      'Laptop refresh on a schedule; productivity never hits a cliff.',
      'Gym membership you actually use; cost per visit makes sense.',
      'Haircuts and basics on autopilot; grooming is not a panic line.',
    ],
    good: [
      'You capped “misc personal” and mostly stay inside it.',
      'Clothing swaps and resale fund refreshes without debt.',
      'One flagship subscription replaced three forgotten ones.',
      'You wait 48 hours on non-essentials; most carts die quietly.',
      'Refurbished gear where smart; warranty still covers bad luck.',
      'Password manager paid yearly once; monthly drip eliminated.',
    ],
    bad: [
      'Silent renewals stack; you pay for services you forgot exist.',
      'Wardrobe leaks via micro-buys; closets full, account thin.',
      'Phone upgrade on impulse financing; monthly creep never leaves.',
      'Cloud storage tiers multiplied; each “just $2” became a choir.',
      'Fast fashion hauls for stress; landfill and ledger both groan.',
      'Kids’ gear outgrows budget; you borrow trouble with BNPL.',
    ],
    terrible: [
      'Broken phone, no repair budget; predatory terms for a replacement.',
      'Buy-now-pay-later chains across categories; minimums become lifestyle.',
      'Identity-ish spending: you shop to feel okay; math does not care.',
      'Collections on utility phone internet stack; basics feel luxury.',
      'Wedding or prom on cards; one night echoes for years.',
      'Cosmetic procedure financing; confidence sold with interest attached.',
    ],
  },
  savings: {
    excellent: [
      'High-yield savings actually earns; emergency and goals both breathe.',
      'Automatic transfers hit before you notice; the account climbs quietly.',
      'You named accounts for goals; progress feels visible, not abstract.',
      'Windfalls land in savings first; lifestyle never saw the deposit.',
      'You ladder CDs or cash when rates make sense; patience paid.',
      'Savings rate rises after debt cleared; the graph finally smiles.',
    ],
    good: [
      'You save something every month even if it is not “enough yet.”',
      'Raises split: half to savings until the fund hits the target.',
      'Round-ups and micro-transfers add up without thinking.',
      'You moved savings off the main bank screen; less temptation.',
      'Tax refund mostly saved; one small treat, no regret.',
      'Side gig income earmarked; it never mixed with spending.',
    ],
    bad: [
      'Savings exists but leaks to “just this once” every quarter.',
      'You save then raid for non-emergencies; the habit never sticks.',
      'Interest on savings is a rounding error; motivation fades.',
      'One big trip drains the cushion; rebuilding feels like starting over.',
      'You keep savings low to avoid “locking money up”; risk rises.',
      'Joint account disagreements; savings stalls in negotiation.',
    ],
    terrible: [
      'Savings account is a fiction; every month starts at zero.',
      'You save then cover overdrafts from the same account.',
      'Fees eat the tiny balance; the bank wins on inertia.',
      'Savings used to float lifestyle; the label lied.',
      'No separate savings; checking is everything until it is not enough.',
      'Gambling or speculative “savings” — volatility dressed as prudence.',
    ],
  },
  indexFunds: {
    excellent: [
      'Broad market index on autopilot; fees near zero, discipline high.',
      'You rebalance yearly without drama; allocation matches the plan.',
      'Dollar-cost averaging through volatility; decades like consistency.',
      'Tax-loss harvesting where appropriate; after-tax returns improve.',
      'You ignore ticker headlines; the index does not care about noise.',
      'Target-date or total-market funds simplify; complexity did not help anyway.',
    ],
    good: [
      'You picked a solid total-market fund and stopped swapping.',
      'Expense ratios compared; you switched once and stayed.',
      '401k default index fund stayed put; inertia accidentally helped.',
      'Small increases after raises; lifestyle did not absorb everything.',
      'You read one good book on indexing; fewer impulse moves followed.',
      'International slice added for diversification; home bias eased.',
    ],
    bad: [
      'You index-hopped every fad ETF; fees and taxes nibbled returns.',
      'Panic sold a broad index once; timing hurt more than stock-picking would have.',
      'Ignored asset location; index funds in taxable without a plan.',
      'Chased “smart beta” without understanding; complexity without edge.',
      'Paused contributions every dip; the best days were often missed.',
      'Concentrated “index” on one sector; concentration risk dressed as passive.',
    ],
    terrible: [
      'Leveraged index products for “sure upside”; math did not agree.',
      'Margin on index ETFs; a normal correction became a margin call.',
      'Raided index holdings for lifestyle; long runway shortened overnight.',
      'Scam “index fund” with hidden fees; the label was marketing.',
      'Borrowed against index portfolio to spend; sequence risk arrived angry.',
      'All-in one narrow index; a single sector winter froze everything.',
    ],
  },
  individualStocks: {
    excellent: [
      'Small “fun money” slice; core wealth stays diversified and boring.',
      'You research patiently; position sizes respect risk.',
      'Dividend growers held for years; compounding did quiet work.',
      'Tax lots tracked; gains harvested with intent, not panic.',
      'You sell winners to rebalance; ego did not veto the plan.',
      'Concentration trimmed after a run-up; discipline beat greed.',
    ],
    good: [
      'A few names you understand; not a casino, not a closet indexer.',
      'You set a max single-stock percent and mostly obey it.',
      'Limit orders and patience; fewer FOMO entries at the bell.',
      'You journal why you bought; fewer mystery positions later.',
      'Small IPO allocation only from play money; downside bounded.',
      'ESPP shares sold on schedule; concentration did not creep.',
    ],
    bad: [
      'Meme trades replace sleep; portfolio became a group chat.',
      'Concentrated in employer stock; job and nest egg correlated.',
      'Average down without thesis; hope became the strategy.',
      'Margin on single names; one headline erased quarters.',
      'You chased analyst targets; revisions always lagged reality.',
      'Tax blindness; short-term gains and wash sales ate edge.',
    ],
    terrible: [
      'One stock became most of net worth; a scandal rewrote the year.',
      'Penny stock “diversification”; liquidity vanished when needed.',
      'Insider-tip fantasy; regulators and losses arrived together.',
      'Options on meme names; defined risk became undefined pain.',
      'You doubled down until broke; pride vetoed every exit.',
      'Borrowed to buy more of a loser; conviction met insolvency.',
    ],
  },
  bonds: {
    excellent: [
      'Bond ladder matches known expenses; rates matter less than timing.',
      'High-quality bonds stabilize the portfolio when stocks sneeze.',
      'You bought duration to match goals; surprises were rare.',
      'I-bonds or TIPS when inflation risk rose; real returns preserved.',
      'Rebalancing sells stocks into bonds after a run; buy low-ish discipline.',
      'Tax-exempt munis fit your bracket; after-tax yield won.',
    ],
    good: [
      'Core bond fund in 401k; boring ballast did its job.',
      'You understand duration enough to not panic on small NAV moves.',
      'Cash + short bonds for near-term needs; stocks stayed long-term.',
      'Credit quality checked; junk did not sneak in as “income.”',
      'Laddered CDs and Treasuries; predictable, if modest.',
      'You did not abandon bonds after one bad year; allocation held.',
    ],
    bad: [
      'Reached for yield; credit risk showed up at the worst time.',
      'Long bonds without horizon match; rate hikes hurt more than planned.',
      'Bond funds treated like cash; liquidity mismatch hurt.',
      'Ignored inflation; nominal safety, real erosion.',
      'Chased “income” funds without reading what generated yield.',
      'Sold bonds at the bottom of a rate cycle; textbook regret.',
    ],
    terrible: [
      'CoCo bonds or exotic structures; called away in stress.',
      'Leveraged bond ETFs; gentle rates became violent losses.',
      'Concentrated in single issuer “safe” bonds; default was “impossible.”',
      'Ponzi labeled fixed income; principal walked out the door.',
      'Borrowed against bond portfolio; margin and duration doubled pain.',
      'Everything in long Treasuries betting one macro thesis; thesis broke.',
    ],
  },
  cds: {
    excellent: [
      'CD ladder for known tuition or taxes; maturity dates align with bills.',
      'Rates locked when attractive; patience beat chasing checking yields.',
      'FDIC limits respected; large sums split cleanly across banks.',
      'Early withdrawal penalties understood; liquidity planned anyway.',
      'You compared APYs once, chose, and stopped obsessing.',
      'Brokered CDs only where you read the fine print; no surprises.',
    ],
    good: [
      'A few CDs anchor cash you truly will not need until date X.',
      'You used CDs instead of risky “yield hacks” for short money.',
      'Renewal alerts set; money did not idle at default bad rates.',
      'Step-up CDs used intentionally; you knew the rules.',
      'Small CD for discipline; out of sight helped behavior.',
      'Mixed CDs and HYSA; right tool per time horizon.',
    ],
    bad: [
      'Long CDs for money you might need; penalties ate returns.',
      'Chased teaser rates; rollover landed in worse products.',
      'Ignored early withdrawal math; “breaking” cost more than staying.',
      'Too many small CDs; admin overhead became its own tax.',
      'Brokered CDs without reading callable terms; called away annoyed.',
      'CDs in taxable while high-rate debt still breathed; order wrong.',
    ],
    terrible: [
      'Exotic CD-linked notes sold as “safe”; principal walked.',
      'Locked everything long; emergency forced fire-sale losses.',
      'Bank failure risk ignored; uninsured amounts vanished in edge cases.',
      'CDs funding lifestyle creep; discipline never arrived.',
      'Rolled endlessly at bad rates; inertia became the enemy.',
      'Predatory renewal terms; autopilot favored the issuer.',
    ],
  },
  crypto: {
    excellent: [
      'Tiny allocation; keys secured; treated as volatile lottery ticket.',
      'You took profits on schedule; greed did not veto exits.',
      'Hardware wallet; no exchange counterparty drama.',
      'Tax lots tracked; IRS surprises avoided.',
      'You never levered crypto; survival mattered more than bragging.',
      'Education before size; scams avoided by skepticism.',
    ],
    good: [
      'Play money only; core plan ignores coin prices.',
      'You use reputable exchanges and 2FA; basics done.',
      'DCA small amounts; volatility became feature not bug.',
      'Stablecoins only for short bridges; not a savings account.',
      'You understand gas and fees; fewer “why is this tiny” moments.',
      'Allocation capped at a percent; rebalancing trimmed runs.',
    ],
    bad: [
      'FOMO size; portfolio became a chart addiction.',
      'Left coins on exchange; hack news became personal stress.',
      'Leverage on volatile assets; liquidation taught physics.',
      'Tax surprises; short-term trades without records.',
      '“Yield farming” without reading smart-contract risk.',
      'Concentrated in one token; narrative changed faster than thesis.',
    ],
    terrible: [
      'Life savings on leverage; one wick erased the decade.',
      'Rug pull; due diligence was a Discord screenshot.',
      'Locked staking with no exit; liquidity died when bills arrived.',
      'Scam wallet seed phrase shared; funds ghosted instantly.',
      'Borrowed to buy the dip that kept dipping.',
      'Ponzi APY; you were exit liquidity.',
    ],
  },
  employerMatch: {
    excellent: [
      'You contribute enough to capture every free dollar; math is emotional.',
      'Cap and match rate understood; paycheck deductions optimized.',
      'Vesting tracked; you did not leave free money on the table early.',
      'Auto-escalation enabled; raises quietly increased deferrals.',
      'You read the SPD once; fewer surprises at open enrollment.',
      'After-tax mega backdoor where available; advanced, disciplined.',
    ],
    good: [
      'At least default deferral; better than zero match captured.',
      'You increased 1% after each raise until hitting the cap.',
      'Spouse plan coordinated; household match maximized.',
      'You avoided high-fee funds inside the plan where alternatives existed.',
      'Rebalanced 401k yearly; drift did not become disaster.',
      'Catch-up contributions planned as birthday approached.',
    ],
    bad: [
      'Leaving match on the table “because cash flow feels tight.”',
      'High-fee annuities inside plan; match partly eaten by costs.',
      'Ignored vesting cliff; job change timing cost thousands.',
      'Paused contributions during bull years; timing hurt twice.',
      'Borrowed from 401k for non-emergency; match growth stalled.',
      'Never updated beneficiaries; paperwork lagged life changes.',
    ],
    terrible: [
      'Zero deferral for years while match existed; compounding cried.',
      'Defaulted 401k loan; taxes and penalties turned help into harm.',
      'Employer stock concentration + match stock; double exposure ignored.',
      'Plan fees ignored for decades; drag erased a chunk of match value.',
      'Scammed out of rollover; “advisor” fees ate the account.',
      'Early withdrawal for lifestyle; penalties plus lost match growth.',
    ],
  },
} as const;
